### ISSUE TITLE
Support ENS resolution.

### ISSUE THREAD

**Issue by hosaka** [enkryptcom/enKrypt#117]
Would be nice to be able to use ENS as a recipient address (perhaps as a wallet name too). [@ethersproject/providers](https://docs.ethers.io/v5/api/providers/provider/#Provider--ens-methods) package provides `resolveName("address.eth")` and `lookupAddress("0x12345")`. Providers supported by this package are: alchemy, etherscan, infura among others. I think ethers is [also used by MetaMask](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/ens/ens.js).

Would it beb acceptable for enkrypt to use this package or there are plans to add ENS resolution to ethvm APIs?

**Comment by hosaka** [comment]
Looks like this was implemented in #138.

**Comment by kvhnuke** [comment]
will be added with #154
