### ISSUE TITLE
Where is the disconnect button?

### ISSUE THREAD

**Issue by nikitindiz** [enkryptcom/enKrypt#169]
Cant find a way to disconnect account from DApp.

Does wallet support this feature?

**Comment by kvhnuke** [comment]
this is currently in the roadmap, will let you know as soon as it is implemented

**Comment by kvhnuke** [comment]
![image](https://github.com/enkryptcom/enKrypt/assets/10602065/4cb68a10-59cc-4f28-97e9-71f88ebe796a)

Disconnect button is next to the address now :)
