### ISSUE TITLE
Enkrypt conflicts with Metamask when dapp tries to connect wallet

### ISSUE THREAD

**Issue by nikitindiz** [enkryptcom/enKrypt#170]
## Environment

macOS Monterey

Google Chrome Version 106.0.5249.103 (Official Build) (arm64)

## Current behavior

If browser has both Enkrypt and Metamask installed. Enkrypt triggers when dapp tries to connect Metamask. Unable to interract with dapp using Metamask when Enkrypt connected to the website.

## Expected behavior

When both Enkrypt and Metamask installed. Metamask opens when Metamask connection requested. Enkrypt opens when Enkrypt connection requested. Wallets interaction is independent.

## Example

wagmi + rainbowkit + @enkryptcom/connector-wagmi

https://github.com/nikitindiz/mm-vs-enkrypt
https://enkrypt-conflicts-metamask-ils0kjrgn-nikitindiz.vercel.app/

When browser has Enkrypt only - works fine. MM only - fine. Both - Enkrypt only works.

**Comment by kvhnuke** [comment]
Unfortunately this is not going to be an easy fix, we made a new EIP 5749 to make this a possibility once that is Final, we have to hope that all extensions will follow that standard
https://eips.ethereum.org/EIPS/eip-5749
