### ISSUE TITLE
Displays spent funds

### ISSUE THREAD

**Issue by wzykubek** [enkryptcom/enKrypt#188]
The wallet displays funds which have been on the address a few days ago and have been spent. Block explorer doesn't show them anymore.

Edit: It happens on Polygon and BSC chain, I don't know if on Ethereum too.

**Comment by wzykubek** [comment]
I don't know, I've been uninstalled this wallet because of huge number of issues... I'm waiting for more stable release and then I will test it again. 

Dnia 9 grudnia 2022 17:58:23 UTC, Kosala Hemachandra ***@***.***> napisał/a:

**Comment by kvhnuke** [comment]
please reopen if you see any issues
