### ISSUE TITLE
Setting up development build

### ISSUE THREAD

**Issue by thoth-seshat** [enkryptcom/enKrypt#226]
Hi,

I'm trying to get everything setup locally to contribute and I noticed that after running `yarn install` It's failing with dependency issues. 

Running: 
node: 16
yarn 3
macosx 13.1

fresh clone of the repo following the read me. 

Removing `yarn.lock` fixes things but I'm assuming we don't want that?

**Comment by thoth-seshat** [comment]
In addition, I'm getting all of these typescript errors when building 

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/122938275/217673005-5aad279f-5ded-4aea-b81b-8c25547d693f.png">

**Comment by thoth-seshat** [comment]
I'm on the `develop` branch and this still seems to be an issue.

**Comment by kvhnuke** [comment]
please run
`yarn install`
`yarn build:all`

then navigate to packages/extension then run `yarn watch`

please reopen if the issue still exists
