### ISSUE TITLE
No fees displayed, all $0

### ISSUE THREAD

**Issue by carloftg** [enkryptcom/enKrypt#267]
Hello, using the brave extension 1.15.0 (latest I suppose) when using the SEND function, there are no fees displayed at all (all are set to $0 see screenshot attached), actually, yesterday when I tried the extension, the fast mode on ethereum fees were displayed as cheaper as the economy's one. Am I missing something in my settings?

![image](https://user-images.githubusercontent.com/52339276/229685608-93943976-1d39-41d3-8254-8279615a526c.png)

**Comment by kvhnuke** [comment]
Hi
Can you please try again with the latest release v1.16.1+

**Comment by kvhnuke** [comment]
please reopen if you still see this issue

**Comment by ItsLuized** [comment]
I still experience this on Chrome but with v1.17.0.

(I want to use Gnosis)

<img width="422" alt="image" src="https://user-images.githubusercontent.com/32660456/235721939-5f53c2dc-e639-469d-a7f6-1aa65b08bbe4.png">
