### ISSUE TITLE
Adding support for PulseChain

### ISSUE THREAD

**Issue by armaccloud** [enkryptcom/enKrypt#290]
PulseChain (pulsechain.com) has just launched.
Can support be added for this chain?
Thanks

**Comment by kvhnuke** [comment]
yes feel free to make a PR 
https://myetherwallet.gitbook.io/enkrypt-documentation/adding-an-evm-network
https://myetherwallet.gitbook.io/enkrypt-documentation/adding-a-substrate-network-to-enkrypt
