### ISSUE TITLE
enKrypt will override Metamask, when launching App

### ISSUE THREAD

**Issue by bingryan** [enkryptcom/enKrypt#303]
uniswap: 

<img width="1532" alt="image" src="https://github.com/enkryptcom/enKrypt/assets/41174435/73f0a2f9-0d16-4912-96e3-eca28717e71b">

**Comment by kvhnuke** [comment]
this is a major issue in ethereum eco system where you cant have 2 browser wallets at the same time, however there will be a fix for all wallets soon 
https://eips.ethereum.org/EIPS/eip-6963

meanwhile you can temporarily disable Enkrypt by going to settings
![image](https://github.com/enkryptcom/enKrypt/assets/10602065/358e2e7f-1ccc-4a1d-83f5-7a01eae3f91c)
turn off Ethereum for 1 hour
