### ISSUE TITLE
Enkrypt - import bitcoin wallet

### ISSUE THREAD

**Issue by jeedee5** [enkryptcom/enKrypt#305]
Hi, 

When I try to import a bitcoin wallet with its private key, it doesn't add the existing bitcoin address, but it looks to be creating a new address... 
Is it not supported to add existing bitcoin addresses?

**Comment by kvhnuke** [comment]
bitcoin has few different kinds of addresses, we only support the current standard which is `segwit` can you post one of your address? I can check which type it is

**Comment by Patish11** [comment]
> Hi, 
> 
> 
> 
> When I try to import a bitcoin wallet with its private key, it doesn't add the existing bitcoin address, but it looks to be creating a new address... 
> 
> Is it not supported to add existing bitcoin addresses?
> 
>
