### ISSUE TITLE
How can I recreate BTC address with BIP39?

### ISSUE THREAD

**Issue by georgjaehnig** [enkryptcom/enKrypt#306]
Enkrypt generates a BTC address that until now I wasn't able to recreate with [Ian Coleman's BIP39 tool](https://iancoleman.io/bip39/).

I expected it to happen with using the BIP84 tab, as this is the only one generating `bc1q...` addresses – but these addresses generated there are different than what Enkrypt generates.

So what setting in https://iancoleman.io/bip39/ shall I set to get the BTC address in Ekrypt?

**Comment by kvhnuke** [comment]
![image](https://github.com/enkryptcom/enKrypt/assets/10602065/902a8baf-0e1f-40a9-a915-ae809804eee3)
