### ISSUE TITLE
Integration of the ZetaChain Athens Test network into the MEV. 

### ISSUE THREAD

**Issue by souveyr** [enkryptcom/enKrypt#328]
ZetaChain; the world's first and only public blockchain that connects all other blockchains (including Bitcoin and DogeCoin).

We have good traction with high marketing value. We have 750k+ members on Discord, 710k+ members on Twitter and 500k+ monthly active testnet participants (link3.to/zetachain). 

MEV's addition of the EVM-compatible ZetaChain network could bring a large influx of users from ZetaChain, which has a large community. I believe this will be a great contribution to MEV. 

Github and dev docs here: https://link3.to/zetachain

Thank you!

**Comment by kvhnuke** [comment]
We dont fasicillitate MEV (Maxima Extractable Value), if you are referring to adding ZetaChain to Enkrypt please follow the guidelines here https://myetherwallet.gitbook.io/enkrypt-documentation/adding-an-evm-network
