### ISSUE TITLE
Recovery phrase recovers only default address

### ISSUE THREAD

**Issue by deepaks-scallopx** [enkryptcom/enKrypt#332]
Hi Team

While using Enkrypt wallet we have come across a bug where on recovering a wallet using recovery phrase only the first address gets recovered by default while all other addresses created using Add Account feature do not show up. 

These accounts show up in order of creation when user again adds new accounts until previously created accounts have been restored to begin with creating new accounts.

Could you please check and feedback on this.

**Comment by kvhnuke** [comment]
Since we do not save any user data on a server side, we are unaware how many addresses you added previously and number of addresses are not associated with the Mnemonic.
currently only way to recover all addresses are by keep adding new address until you recover the address you need
