### ISSUE TITLE
Cannot add manual network because the popup closes

### ISSUE THREAD

**Issue by SamWilsn** [enkryptcom/enKrypt#335]
## Environment

 Key | Value |
-|-|
OS | Linux (`Linux gentoo 6.1.38-gentoo-dist #1 SMP PREEMPT_DYNAMIC Wed Jul 19 19:57:28 EDT 2023 x86_64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz GenuineIntel GNU/Linux`) |
`$XDG_SESSION_TYPE` | `x11` |
Browser | Chromium Version 114.0.5735.198 (Official Build) (64-bit) |
Extension | Enkrypt 1.24.0 |

## What happened?

I'm trying to add a custom chain, but when I switch Chromium windows to paste the RPC information, the wallet popup closes.

https://github.com/enkryptcom/enKrypt/assets/57262657/ec203795-ed71-4502-853f-d1d175c64f61

If you're curious, the dapp is the [Wallet Test Framework](https://github.com/wallet-test-framework/framework).

**Comment by kvhnuke** [comment]
can you try copying the URL first,
unfortunately this is due to Chrome window getting unfocused, you just need to copy the URL since we automatically get all other info
