### ISSUE TITLE
Bitcoin address import

### ISSUE THREAD

**Issue by Patish11** [enkryptcom/enKrypt#348]
Hi, 

When I try to import a bitcoin wallet with its private key, it doesn't add the existing bitcoin address, but it looks to be creating a new address... 
Is it not supported to add existing bitcoin addresses?
 

_Originally posted by @jeedee5 in https://github.com/enkryptcom/enKrypt/issues/305_

**Comment by kvhnuke** [comment]
can you post one of your addresses, I can check which type of address it is
