### ISSUE TITLE
Error when used with @web3-onboard/injected-wallets

### ISSUE THREAD

**Issue by daniel-ivanco** [enkryptcom/enKrypt#364]
When using Encrypt in combination with [web3onboard injected module](https://www.npmjs.com/package/@web3-onboard/injected-wallets) it throws this error:

```Uncaught (in promise) TypeError: 'get' on proxy: property 'request' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected 'function () { [native code] }' but got 'function () { [native code] }')```

NOTE: other injected wallets work without problems

**Comment by kvhnuke** [comment]
is there a demo site I can try this out?
