### ISSUE TITLE
Add the ability to connect hardware wallet directly

### ISSUE THREAD

**Issue by zelosleone** [enkryptcom/enKrypt#367]
without making a new wallet, it would be better to just use ledger/trezor instead of creating a hot wallet then connect the cold wallet. At least as an option.

**Comment by zelosleone** [comment]
> this is already an option if you expand the accounts list, there is an option to add hardware wallet

It seems like i couldnt explain the issue clearly. I am talking about without setting up a wallet first, directly connecting via ledger. Like, no seed phrase, nothing, onboarding is done via ledger connection

**Comment by jobukkit** [comment]
Yes, it's silly that you're forced to write down a seed phrase for a hot wallet you don't want to use, just so you can add your Trezor or Ledger afterwards. The lack of Polkadot support on Trezor may be a reason for this, though.

**Comment by vrwim** [comment]
If I try to add a hardware wallet, I only see the option for Trezor. I am using Safari as a browser.

**Comment by jobukkit** [comment]
> If I try to add a hardware wallet, I only see the option for Trezor. I am using Safari as a browser.

Trezor support is broken too on Safari. The Ledger button only shows on the Chrome extension.
