### ISSUE TITLE
Import account from other wallet does nothing

### ISSUE THREAD

**Issue by luzemario** [enkryptcom/enKrypt#399]
After adding your keystore file, nothing happens and the account is not imported

Steps to reproduce:
1. Open Enkrypt
2. Click on your account on the top
3. Click on Import Account from another wallet
4. Choose keystore file
5. Click twice on the file to open it
6. Nothing happens and the account is not imported (the file selection screen is closed, but the account is not imported and there are no errors).

**Comment by luzemario** [comment]
Used Firefox extension
Firefox 115.7.0esr (64-bits)

**Comment by kvhnuke** [comment]
what operating system are you on?

**Comment by luzemario** [comment]
`Linux desk 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux`

Devuan Daedalus (5.0)

**Comment by kvhnuke** [comment]
> `Linux desk 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux`
> 
> Devuan Daedalus (5.0), mostly Debian 12 without systemd

yea there is an issue on linux where opening a file closes the extension window popup, you can get around it by opening the extension then right click inspect (inspect window will open you can ignore that) now go ahead and try to import the wallet

**Comment by CesarFRR** [comment]
"yea there is an issue on linux where opening a file closes the extension window popup, you can get around it by opening the extension then right click inspect (inspect window will open you can ignore that) now go ahead and try to import the wallet"

YISUS, THNK YOU SO MUCH IT WORKS!
