### ISSUE TITLE
Contract reverts are not shown to user

### ISSUE THREAD

**Issue by jxom** [enkryptcom/enKrypt#417]
If a contract interaction is expected to revert, no information (ie. revert message) is shown to the user. I would expect the "Send" button to be disabled, with an error message shown to the user.

Can reproduce by performing `mint(69)` on this contract: https://etherscan.io/address/0xFBA3912Ca04dd458c843e2EE08967fC04f3579c2#writeContract.

<img width="462" alt="CleanShot 2024-03-22 at 17 03 22@2x" src="https://github.com/enkryptcom/enKrypt/assets/7336481/ab1fc1f5-354a-4cbc-aab1-df8eb1afe1de">

**Comment by kvhnuke** [comment]
https://github.com/enkryptcom/enKrypt/pull/470/commits/53e527b64b037ab7e7cbe09d65ce68d61257c108

fixed
