### ISSUE TITLE
Please add support for Telos EVM

### ISSUE THREAD

**Issue by jbuice** [enkryptcom/enKrypt#466]
Name: Telos EVM
Symbol: TLOS
Mainnet ChainID: 40
Testnet ChainID: 41
RPC: https://mainnet15.telos.net/evm
Explorer: https://teloscan.io

Chain Socials:
X: https://x.com/hellotelos
Telegram: @HelloTelos

Logo URL: https://www.telos.net/community-resources
Chainlist: https://chainlist.org/chain/40

Additional Info (optional: audits, bridges, etc)

Contract Audits: https://sentnl.io/audits/telos-0
Bridge : https://bridge.telos.net/bridge (LayerZero Bridge)

**Comment by kvhnuke** [comment]
https://github.com/enkryptcom/enKrypt/pull/470/commits/9896d91ce660c0dc13af912eaa4d83b2172923e5
